language: java
jdk:
- oraclejdk8
env:
  global:
    - secure: "OFDXpkwrg2hiHMoel/Q8AUV0CEC1Bz/9c96IcBX9DlsFcDv+BhCUHg6b6VqVgAZAnLD7YbJBc9KeFa6YO78LtUSAFp1+lg0dgP2DWlo+lRDu9EKEaLa7cmD5t/UicmUil4X/7IMfkKJFsgq22pZ636bjki7r+ZClx0MHFZKWmn6Ea+633v2JjQJTLGIibt/Zb924QKUPW5CI49wqvq0S+l/4v2f0/5Z4cDPGkoXAtsVyyCBNkorSPfYRrH6xPOfCdnVce6LcuoHxqLEwBoJNrkbWfCEDmFa/xOmmr3a1FLEPlJxuU78AVO4gRaYt5LLe1mKR1amkN9RrtkHGBiOST+2Su9IOIarVRUM7g0A3kZPul4Ek4WLvqyTiUC7YUvKVikdNCurBuwpXTrloZDDcDyv7luqQlPG0lkq3CByt+CdT4uRJTcK0oEH1L83sg+gvp/5mL28UUaW+Hj8H65pPMb4w6J5OfKRoiRkMvWBQEU1CT73KBZargT5myQxwbdrbbxeXyIZv61NzE5dfb/kLhRTVZdpE9gYAHpHI0V7VlN1LjrItprXOmxUHUHOsQVruIpd5ljOaWmbPNTsvLNkUHajPY6b3X04isTotndgWZLb7IaLJId9sO0tdrsh2Hi5FNhLW5DwVvHkDCPUdF8PCBSTvm81uhx38h1+LTNRdWtU="
    - # ^^ GPG_KEY_NAME
    - secure: "ZMLV3nhRcCf6Oju/C/IFbOWZMMpdXllDKpwkF+cMLIUXXR3ZvzR9AIBmmi7IRpup8BUbpWKiY/Br8CP88nBwhpTg3+sA8roxP+CIszL1E598FZ7TSD67U0iw3EbZgfXdHUThVj+CRrkrCCPkqxno/Cuhi1zhgm8GCabQpsTgYCXgIyXmwI1WmZNn7wpdiVllpMAfft1JD32QiEi5txvpjqtx3VAky5Hny1GtUd9Qi7gavlbHV6i0yXWODbtwaHeRQYwQH+yJJTZYQ6mMcL23tp3ZBuiGwSY3H6K++pAM3Pcc2e1lt9UkSkXh7NmA+ZrZ2w+KlydpJAspKwgC/m+gV5OtdDV8VIej9vDaMyPoXmIn4NdSRFwfYCaz2CfoLc0+zXoKLhzzVm1AR4sErMv7h3VlLAsisPXhGdcci8DziN48TTkVte5qz7gni1YonWypSr5ZnXIvTDchyqHmnLehA0ndi5uWi9Yup9JoOSDcXJAtwoWKP68iSgz8kbbSN4wXdbOaOtnWMB/UV5eQGjIluEWgxRZrnefSqpNPCC+7c+EReNRoZIBTKWMwk9EqUEPS47262pnwYZFabLmU9l1CwHkOyCPeFZEJgEUQWA91UEMPxuB0gTAuMklmX15kxHnmNUrqG0nd0oXbtVtWTgd/cRWWrRnAkqaHTg1gWM8ufsw="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./travis/before_deploy.sh
  - ./travis/deploy.sh
